---
# Source: neo4j/templates/readreplicas-dns.yaml
# This service is intended for clients running in kubernetes to connect to the
# cluster replica set.  This distinguishes it from discovery-lb which is about 
# cluster formation and internal communication.
apiVersion: v1
kind: Service
metadata:
  name: neo4j-neo4j-replica
  labels:
    neo4j.com/bolt: "true"
    neo4j.com/http: "true"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "neo4j"
    helm.sh/chart: "neo4j-4.4.5"
    app.kubernetes.io/name: neo4j-neo4j-replica
    app.kubernetes.io/component: replica
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-http
      port: 7474
      targetPort: 7474
    - name: tcp-bolt
      port: 7687
      targetPort: 7687
    - name: tcp-https
      port: 7473
      targetPort: 7473
  selector:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/instance: "neo4j"
    app.kubernetes.io/component: replica
