apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- charts/kube-state-metrics/templates/clusterrolebinding.yaml
- charts/kube-state-metrics/templates/deployment.yaml
- charts/kube-state-metrics/templates/role.yaml
- charts/kube-state-metrics/templates/service.yaml
- charts/kube-state-metrics/templates/serviceaccount.yaml
- templates/alertmanager/clusterrole.yaml
- templates/alertmanager/clusterrolebinding.yaml
- templates/alertmanager/cm.yaml
- templates/alertmanager/deploy.yaml
- templates/alertmanager/pvc.yaml
- templates/alertmanager/service.yaml
- templates/alertmanager/serviceaccount.yaml
- templates/node-exporter/daemonset.yaml
- templates/node-exporter/serviceaccount.yaml
- templates/node-exporter/svc.yaml
- templates/pushgateway/clusterrole.yaml
- templates/pushgateway/clusterrolebinding.yaml
- templates/pushgateway/deploy.yaml
- templates/pushgateway/service.yaml
- templates/pushgateway/serviceaccount.yaml
- templates/server/clusterrole.yaml
- templates/server/clusterrolebinding.yaml
- templates/server/cm.yaml
- templates/server/deploy.yaml
- templates/server/pvc.yaml
- templates/server/service.yaml
- templates/server/serviceaccount.yaml
