version: '3'

services:
  neo4j:
    image: neo4j:enterprise
    env_file:
      - .env.neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
  graphite:
      image: graphiteapp/graphite-statsd
      ports:
      - 8080:80  # Nginx
      - "2003-2004:2003-2004" # Carbon Reciver
      - "2023-2024:2023-2024" # Carbon Aggregator
      - "8125:8125/udp" # Statsd
      - "8126:8126" # StatsD Admin
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

