---
# Source: prometheus/templates/alertmanager/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: prometheus
    chart: prometheus-15.9.1
    heritage: Helm
  name: prometheus-alertmanager
  namespace: default
  annotations:
    {}
