apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>  
      @type tail  
      format json
      time_key time
      time_type string
      time_format %F %T.%L%z
      path /data/logs/*.log
      pos_file /var/log/fluentd/fluentd.pos 
      tag neo4j.*
    </source>
    <filter neo4j.*>
      @type parser
      key_name log
      reserve_data true
      <parse>
        @type json
      </parse>
    </filter>
    <filter neo4j.*>
      @type record_transformer
      <record>
        hostname "#{Socket.gethostname}"
        tag ${tag}
      </record>
    </filter>

    <match **>
      @type elasticsearch
      host elasticsearch-master
      port 9200
      logstash_format true
      logstash_prefix neo4j
      flush_interval 1s
    </match>